# Generated by Django 3.2 on 2021-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_student_roll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='None', upload_to='pics'),
            preserve_default=False,
        ),
    ]
